import static org.junit.Assert.assertEquals;
import static org.junit.Assert.assertTrue;

import org.junit.Before;
import org.junit.Test;

import java.io.StringReader;


import controller.Controller;
import controller.DungeonController;
import dungeon.DungeonMonsterImpl;
import dungeon.DungeonWithMonster;


/**
 * This class consists of all the junit tests in order to test the functionality for the controller.
 */
public class ControllerTest {
  private DungeonWithMonster dungeon;

  @Before
  public void setup() {
    dungeon = new DungeonMonsterImpl(3, 3, 0, 30,
            false, 2, 4);
  }

  @Test(expected = IllegalArgumentException.class)
  public void testInvalidModel() {
    StringReader input = new StringReader("m s m e");
    Appendable log = new StringBuffer();
    DungeonController controller = new Controller(input, log);
    controller.play(null);
  }

  @Test(expected = IllegalArgumentException.class)
  public void testInvalidReadableAppendable() {
    DungeonController controller = new Controller(null, null);
  }

  @Test
  public void testIndependentController() {
    StringReader input = new StringReader("m n s w 1 m e m n p m e m s m s");
    StringBuffer log = new StringBuffer();
    DungeonController controller = new Controller(input, log);
    MockModel model = new MockModel(log);
    controller.play(model);

    assertTrue(log.toString().contains("Move command called"));
    assertTrue(log.toString().contains("Shoot arrow called"));
    assertTrue(log.toString().contains("Inside has arrows"));
    assertTrue(log.toString().contains("Inside has treasure"));
  }

  @Test
  public void testGameQuit() {
    StringReader input = new StringReader("Q");
    Appendable log = new StringBuffer();
    DungeonController controller = new Controller(input, log);
    controller.play(dungeon);
    assertEquals("\nName: Player1\n"
            + "Arrow Count :3\n"
            + "No treasure collected yet! \n"
            + "Location Description :\n"
            + "Location id :7\n"
            + "Location type :Cave\n"
            + "Arrows at location 0\n"
            + "The connections for the location are :\n"
            + "NORTH: ID -> 4\n"
            + "No treasure in this location\n"
            + "Enter your choice: Move{m}, Shoot Arrow{s}, Pick{p}, Quit{q}:\n"
            + "\n"
            + "Quitting game !", log.toString());
  }

  @Test
  public void testInvalidMove() {
    StringReader input = new StringReader("m n one two o z yx q");
    Appendable log = new StringBuffer();
    DungeonController controller = new Controller(input, log);
    controller.play(dungeon);
    assertEquals("\nName: Player1\n"
            + "Arrow Count :3\n"
            + "No treasure collected yet! \n"
            + "Location Description :\n"
            + "Location id :7\n"
            + "Location type :Cave\n"
            + "Arrows at location 0\n"
            + "The connections for the location are :\n"
            + "NORTH: ID -> 4\n"
            + "No treasure in this location\n"
            + "Enter your choice: Move{m}, Shoot Arrow{s}, Pick{p}, Quit{q}:\n"
            + "\n"
            + "In which direction you want to move? [NORTH]\n"
            + "\n"
            + "Name: Player1\n"
            + "Arrow Count :3\n"
            + "No treasure collected yet! \n"
            + "Location Description :\n"
            + "Location id :4\n"
            + "Location type :Tunnel\n"
            + "Arrows at location 0\n"
            + "The connections for the location are :\n"
            + "SOUTH: ID -> 7\n"
            + "EAST: ID -> 5\n"
            + "No treasure in this location\n"
            + "Enter your choice: Move{m}, Shoot Arrow{s}, Pick{p}, Quit{q}:\n"
            + "\n"
            + "Invalid move.\n"
            + "Name: Player1\n"
            + "Arrow Count :3\n"
            + "No treasure collected yet! \n"
            + "Location Description :\n"
            + "Location id :4\n"
            + "Location type :Tunnel\n"
            + "Arrows at location 0\n"
            + "The connections for the location are :\n"
            + "SOUTH: ID -> 7\n"
            + "EAST: ID -> 5\n"
            + "No treasure in this location\n"
            + "Enter your choice: Move{m}, Shoot Arrow{s}, Pick{p}, Quit{q}:\n"
            + "\n"
            + "Invalid move.\n"
            + "Name: Player1\n"
            + "Arrow Count :3\n"
            + "No treasure collected yet! \n"
            + "Location Description :\n"
            + "Location id :4\n"
            + "Location type :Tunnel\n"
            + "Arrows at location 0\n"
            + "The connections for the location are :\n"
            + "SOUTH: ID -> 7\n"
            + "EAST: ID -> 5\n"
            + "No treasure in this location\n"
            + "Enter your choice: Move{m}, Shoot Arrow{s}, Pick{p}, Quit{q}:\n"
            + "\n"
            + "Invalid move.\n"
            + "Name: Player1\n"
            + "Arrow Count :3\n"
            + "No treasure collected yet! \n"
            + "Location Description :\n"
            + "Location id :4\n"
            + "Location type :Tunnel\n"
            + "Arrows at location 0\n"
            + "The connections for the location are :\n"
            + "SOUTH: ID -> 7\n"
            + "EAST: ID -> 5\n"
            + "No treasure in this location\n"
            + "Enter your choice: Move{m}, Shoot Arrow{s}, Pick{p}, Quit{q}:\n"
            + "\n"
            + "Invalid move.\n"
            + "Name: Player1\n"
            + "Arrow Count :3\n"
            + "No treasure collected yet! \n"
            + "Location Description :\n"
            + "Location id :4\n"
            + "Location type :Tunnel\n"
            + "Arrows at location 0\n"
            + "The connections for the location are :\n"
            + "SOUTH: ID -> 7\n"
            + "EAST: ID -> 5\n"
            + "No treasure in this location\n"
            + "Enter your choice: Move{m}, Shoot Arrow{s}, Pick{p}, Quit{q}:\n"
            + "\n"
            + "Invalid move.\n"
            + "Name: Player1\n"
            + "Arrow Count :3\n"
            + "No treasure collected yet! \n"
            + "Location Description :\n"
            + "Location id :4\n"
            + "Location type :Tunnel\n"
            + "Arrows at location 0\n"
            + "The connections for the location are :\n"
            + "SOUTH: ID -> 7\n"
            + "EAST: ID -> 5\n"
            + "No treasure in this location\n"
            + "Enter your choice: Move{m}, Shoot Arrow{s}, Pick{p}, Quit{q}:\n"
            + "\n"
            + "Quitting game !", log.toString());
  }

  @Test
  public void testInvalidMoveCommand() {
    StringReader input = new StringReader("m s one two");
    Appendable log = new StringBuffer();
    DungeonController controller = new Controller(input, log);
    controller.play(dungeon);
    assertEquals("\nName: Player1\n"
            + "Arrow Count :3\n"
            + "No treasure collected yet! \n"
            + "Location Description :\n"
            + "Location id :7\n"
            + "Location type :Cave\n"
            + "Arrows at location 0\n"
            + "The connections for the location are :\n"
            + "NORTH: ID -> 4\n"
            + "No treasure in this location\n"
            + "Enter your choice: Move{m}, Shoot Arrow{s}, Pick{p}, Quit{q}:\n"
            + "\n"
            + "In which direction you want to move? [NORTH]\n"
            + "\n"
            + "Name: Player1\n"
            + "Arrow Count :3\n"
            + "No treasure collected yet! \n"
            + "Location Description :\n"
            + "Location id :7\n"
            + "Location type :Cave\n"
            + "Arrows at location 0\n"
            + "The connections for the location are :\n"
            + "NORTH: ID -> 4\n"
            + "No treasure in this location\n"
            + "Enter your choice: Move{m}, Shoot Arrow{s}, Pick{p}, Quit{q}:\n"
            + "\n"
            + "Invalid move.\n"
            + "Name: Player1\n"
            + "Arrow Count :3\n"
            + "No treasure collected yet! \n"
            + "Location Description :\n"
            + "Location id :7\n"
            + "Location type :Cave\n"
            + "Arrows at location 0\n"
            + "The connections for the location are :\n"
            + "NORTH: ID -> 4\n"
            + "No treasure in this location\n"
            + "Enter your choice: Move{m}, Shoot Arrow{s}, Pick{p}, Quit{q}:\n"
            + "\n"
            + "Invalid move.\n"
            + "Name: Player1\n"
            + "Arrow Count :3\n"
            + "No treasure collected yet! \n"
            + "Location Description :\n"
            + "Location id :7\n"
            + "Location type :Cave\n"
            + "Arrows at location 0\n"
            + "The connections for the location are :\n"
            + "NORTH: ID -> 4\n"
            + "No treasure in this location\n"
            + "Enter your choice: Move{m}, Shoot Arrow{s}, Pick{p}, Quit{q}:\n", log.toString());

  }

  @Test
  public void testGarbageInput() {
    StringReader input = new StringReader("zero two xxx");
    Appendable log = new StringBuffer();
    DungeonController controller = new Controller(input, log);
    controller.play(dungeon);
    assertEquals("\n"
            + "Name: Player1\n"
            + "Arrow Count :3\n"
            + "No treasure collected yet! \n"
            + "Location Description :\n"
            + "Location id :7\n"
            + "Location type :Cave\n"
            + "Arrows at location 0\n"
            + "The connections for the location are :\n"
            + "NORTH: ID -> 4\n"
            + "No treasure in this location\n"
            + "Enter your choice: Move{m}, Shoot Arrow{s}, Pick{p}, Quit{q}:\n"
            + "\n"
            + "Invalid move.\n"
            + "Name: Player1\n"
            + "Arrow Count :3\n"
            + "No treasure collected yet! \n"
            + "Location Description :\n"
            + "Location id :7\n"
            + "Location type :Cave\n"
            + "Arrows at location 0\n"
            + "The connections for the location are :\n"
            + "NORTH: ID -> 4\n"
            + "No treasure in this location\n"
            + "Enter your choice: Move{m}, Shoot Arrow{s}, Pick{p}, Quit{q}:\n"
            + "\n"
            + "Invalid move.\n"
            + "Name: Player1\n"
            + "Arrow Count :3\n"
            + "No treasure collected yet! \n"
            + "Location Description :\n"
            + "Location id :7\n"
            + "Location type :Cave\n"
            + "Arrows at location 0\n"
            + "The connections for the location are :\n"
            + "NORTH: ID -> 4\n"
            + "No treasure in this location\n"
            + "Enter your choice: Move{m}, Shoot Arrow{s}, Pick{p}, Quit{q}:\n"
            + "\n"
            + "Invalid move.\n"
            + "Name: Player1\n"
            + "Arrow Count :3\n"
            + "No treasure collected yet! \n"
            + "Location Description :\n"
            + "Location id :7\n"
            + "Location type :Cave\n"
            + "Arrows at location 0\n"
            + "The connections for the location are :\n"
            + "NORTH: ID -> 4\n"
            + "No treasure in this location\n"
            + "Enter your choice: Move{m}, Shoot Arrow{s}, Pick{p}, Quit{q}:\n", log.toString());
  }

  @Test
  public void testMoveCommand() {
    StringReader input = new StringReader("m n m e q");
    Appendable log = new StringBuffer();
    DungeonController controller = new Controller(input, log);
    controller.play(dungeon);
    assertEquals("\nName: Player1\n"
            + "Arrow Count :3\n"
            + "No treasure collected yet! \n"
            + "Location Description :\n"
            + "Location id :7\n"
            + "Location type :Cave\n"
            + "Arrows at location 0\n"
            + "The connections for the location are :\n"
            + "NORTH: ID -> 4\n"
            + "No treasure in this location\n"
            + "Enter your choice: Move{m}, Shoot Arrow{s}, Pick{p}, Quit{q}:\n"
            + "\n"
            + "In which direction you want to move? [NORTH]\n"
            + "\n"
            + "Name: Player1\n"
            + "Arrow Count :3\n"
            + "No treasure collected yet! \n"
            + "Location Description :\n"
            + "Location id :4\n"
            + "Location type :Tunnel\n"
            + "Arrows at location 0\n"
            + "The connections for the location are :\n"
            + "SOUTH: ID -> 7\n"
            + "EAST: ID -> 5\n"
            + "No treasure in this location\n"
            + "Enter your choice: Move{m}, Shoot Arrow{s}, Pick{p}, Quit{q}:\n"
            + "\n"
            + "In which direction you want to move? [SOUTH, EAST]\n"
            + "\n"
            + "Name: Player1\n"
            + "Arrow Count :3\n"
            + "No treasure collected yet! \n"
            + "Location Description :\n"
            + "Location id :5\n"
            + "Location type :Tunnel\n"
            + "Arrows at location 0\n"
            + "The connections for the location are :\n"
            + "NORTH: ID -> 2\n"
            + "WEST: ID -> 4\n"
            + "No treasure in this location\n"
            + "There is a weak smell of something deadly nearby\n"
            + "Enter your choice: Move{m}, Shoot Arrow{s}, Pick{p}, Quit{q}:\n"
            + "\n"
            + "Quitting game !", log.toString());
  }

  @Test
  public void testPickTreasureCommand() {
    StringReader input = new StringReader("m n m e m n p q");
    Appendable log = new StringBuffer();
    DungeonController controller = new Controller(input, log);
    controller.play(dungeon);
    assertEquals("\nName: Player1\n"
            + "Arrow Count :3\n"
            + "No treasure collected yet! \n"
            + "Location Description :\n"
            + "Location id :7\n"
            + "Location type :Cave\n"
            + "Arrows at location 0\n"
            + "The connections for the location are :\n"
            + "NORTH: ID -> 4\n"
            + "No treasure in this location\n"
            + "Enter your choice: Move{m}, Shoot Arrow{s}, Pick{p}, Quit{q}:\n"
            + "\n"
            + "In which direction you want to move? [NORTH]\n"
            + "\n"
            + "Name: Player1\n"
            + "Arrow Count :3\n"
            + "No treasure collected yet! \n"
            + "Location Description :\n"
            + "Location id :4\n"
            + "Location type :Tunnel\n"
            + "Arrows at location 0\n"
            + "The connections for the location are :\n"
            + "SOUTH: ID -> 7\n"
            + "EAST: ID -> 5\n"
            + "No treasure in this location\n"
            + "Enter your choice: Move{m}, Shoot Arrow{s}, Pick{p}, Quit{q}:\n"
            + "\n"
            + "In which direction you want to move? [SOUTH, EAST]\n"
            + "\n"
            + "Name: Player1\n"
            + "Arrow Count :3\n"
            + "No treasure collected yet! \n"
            + "Location Description :\n"
            + "Location id :5\n"
            + "Location type :Tunnel\n"
            + "Arrows at location 0\n"
            + "The connections for the location are :\n"
            + "NORTH: ID -> 2\n"
            + "WEST: ID -> 4\n"
            + "No treasure in this location\n"
            + "There is a weak smell of something deadly nearby\n"
            + "Enter your choice: Move{m}, Shoot Arrow{s}, Pick{p}, Quit{q}:\n"
            + "\n"
            + "In which direction you want to move? [NORTH, WEST]\n"
            + "\n"
            + "Name: Player1\n"
            + "Arrow Count :3\n"
            + "No treasure collected yet! \n"
            + "Location Description :\n"
            + "Location id :2\n"
            + "Location type :Cave\n"
            + "Arrows at location 0\n"
            + "The connections for the location are :\n"
            + "SOUTH: ID -> 5\n"
            + "EAST: ID -> 3\n"
            + "WEST: ID -> 1\n"
            + "The treasure at the location is\n"
            + "RUBY\n"
            + "There is a strong deadly smell.\n"
            + "Enter your choice: Move{m}, Shoot Arrow{s}, Pick{p}, Quit{q}:\n"
            + "\n"
            + "You picked the treasure present at the location.\n"
            + "Name: Player1\n"
            + "Arrow Count :3\n"
            + "Treasure Collected :\n"
            + "RUBY: 1\n"
            + "Location Description :\n"
            + "Location id :2\n"
            + "Location type :Cave\n"
            + "Arrows at location 0\n"
            + "The connections for the location are :\n"
            + "SOUTH: ID -> 5\n"
            + "EAST: ID -> 3\n"
            + "WEST: ID -> 1\n"
            + "No treasure in this location\n"
            + "There is a strong deadly smell.\n"
            + "Enter your choice: Move{m}, Shoot Arrow{s}, Pick{p}, Quit{q}:\n"
            + "\n"
            + "Quitting game !", log.toString());
  }

  @Test
  public void testPickArrowsCommand() {
    StringReader input = new StringReader("m n m e m n p m e m s m s p q");
    Appendable log = new StringBuffer();
    DungeonController controller = new Controller(input, log);
    controller.play(dungeon);
    assertEquals("\nName: Player1\n"
            + "Arrow Count :3\n"
            + "No treasure collected yet! \n"
            + "Location Description :\n"
            + "Location id :7\n"
            + "Location type :Cave\n"
            + "Arrows at location 0\n"
            + "The connections for the location are :\n"
            + "NORTH: ID -> 4\n"
            + "No treasure in this location\n"
            + "Enter your choice: Move{m}, Shoot Arrow{s}, Pick{p}, Quit{q}:\n"
            + "\n"
            + "In which direction you want to move? [NORTH]\n"
            + "\n"
            + "Name: Player1\n"
            + "Arrow Count :3\n"
            + "No treasure collected yet! \n"
            + "Location Description :\n"
            + "Location id :4\n"
            + "Location type :Tunnel\n"
            + "Arrows at location 0\n"
            + "The connections for the location are :\n"
            + "SOUTH: ID -> 7\n"
            + "EAST: ID -> 5\n"
            + "No treasure in this location\n"
            + "Enter your choice: Move{m}, Shoot Arrow{s}, Pick{p}, Quit{q}:\n"
            + "\n"
            + "In which direction you want to move? [SOUTH, EAST]\n"
            + "\n"
            + "Name: Player1\n"
            + "Arrow Count :3\n"
            + "No treasure collected yet! \n"
            + "Location Description :\n"
            + "Location id :5\n"
            + "Location type :Tunnel\n"
            + "Arrows at location 0\n"
            + "The connections for the location are :\n"
            + "NORTH: ID -> 2\n"
            + "WEST: ID -> 4\n"
            + "No treasure in this location\n"
            + "There is a weak smell of something deadly nearby\n"
            + "Enter your choice: Move{m}, Shoot Arrow{s}, Pick{p}, Quit{q}:\n"
            + "\n"
            + "In which direction you want to move? [NORTH, WEST]\n"
            + "\n"
            + "Name: Player1\n"
            + "Arrow Count :3\n"
            + "No treasure collected yet! \n"
            + "Location Description :\n"
            + "Location id :2\n"
            + "Location type :Cave\n"
            + "Arrows at location 0\n"
            + "The connections for the location are :\n"
            + "SOUTH: ID -> 5\n"
            + "EAST: ID -> 3\n"
            + "WEST: ID -> 1\n"
            + "The treasure at the location is\n"
            + "RUBY\n"
            + "There is a strong deadly smell.\n"
            + "Enter your choice: Move{m}, Shoot Arrow{s}, Pick{p}, Quit{q}:\n"
            + "\n"
            + "You picked the treasure present at the location.\n"
            + "Name: Player1\n"
            + "Arrow Count :3\n"
            + "Treasure Collected :\n"
            + "RUBY: 1\n"
            + "Location Description :\n"
            + "Location id :2\n"
            + "Location type :Cave\n"
            + "Arrows at location 0\n"
            + "The connections for the location are :\n"
            + "SOUTH: ID -> 5\n"
            + "EAST: ID -> 3\n"
            + "WEST: ID -> 1\n"
            + "No treasure in this location\n"
            + "There is a strong deadly smell.\n"
            + "Enter your choice: Move{m}, Shoot Arrow{s}, Pick{p}, Quit{q}:\n"
            + "\n"
            + "In which direction you want to move? [SOUTH, EAST, WEST]\n"
            + "\n"
            + "Name: Player1\n"
            + "Arrow Count :3\n"
            + "Treasure Collected :\n"
            + "RUBY: 1\n"
            + "Location Description :\n"
            + "Location id :3\n"
            + "Location type :Tunnel\n"
            + "Arrows at location 0\n"
            + "The connections for the location are :\n"
            + "SOUTH: ID -> 6\n"
            + "WEST: ID -> 2\n"
            + "No treasure in this location\n"
            + "There is a weak smell of something deadly nearby\n"
            + "Enter your choice: Move{m}, Shoot Arrow{s}, Pick{p}, Quit{q}:\n"
            + "\n"
            + "In which direction you want to move? [SOUTH, WEST]\n"
            + "\n"
            + "Name: Player1\n"
            + "Arrow Count :3\n"
            + "Treasure Collected :\n"
            + "RUBY: 1\n"
            + "Location Description :\n"
            + "Location id :6\n"
            + "Location type :Tunnel\n"
            + "Arrows at location 0\n"
            + "The connections for the location are :\n"
            + "SOUTH: ID -> 9\n"
            + "NORTH: ID -> 3\n"
            + "No treasure in this location\n"
            + "There is a weak smell of something deadly nearby\n"
            + "Enter your choice: Move{m}, Shoot Arrow{s}, Pick{p}, Quit{q}:\n"
            + "\n"
            + "In which direction you want to move? [SOUTH, NORTH]\n"
            + "\n"
            + "Name: Player1\n"
            + "Arrow Count :3\n"
            + "Treasure Collected :\n"
            + "RUBY: 1\n"
            + "Location Description :\n"
            + "Location id :9\n"
            + "Location type :Tunnel\n"
            + "Arrows at location 1\n"
            + "The connections for the location are :\n"
            + "NORTH: ID -> 6\n"
            + "WEST: ID -> 8\n"
            + "No treasure in this location\n"
            + "There is a strong deadly smell.\n"
            + "Enter your choice: Move{m}, Shoot Arrow{s}, Pick{p}, Quit{q}:\n"
            + "\n"
            + "You picked the arrows present at the location.\n"
            + "Name: Player1\n"
            + "Arrow Count :4\n"
            + "Treasure Collected :\n"
            + "RUBY: 1\n"
            + "Location Description :\n"
            + "Location id :9\n"
            + "Location type :Tunnel\n"
            + "Arrows at location 0\n"
            + "The connections for the location are :\n"
            + "NORTH: ID -> 6\n"
            + "WEST: ID -> 8\n"
            + "No treasure in this location\n"
            + "There is a strong deadly smell.\n"
            + "Enter your choice: Move{m}, Shoot Arrow{s}, Pick{p}, Quit{q}:\n"
            + "\n"
            + "Quitting game !", log.toString());
  }

  @Test
  public void testShootCommand() {
    StringReader input = new StringReader("m n m e m n p m e m s m s p s w 1 q");
    Appendable log = new StringBuffer();
    DungeonController controller = new Controller(input, log);
    controller.play(dungeon);
    assertEquals("\nName: Player1\n"
            + "Arrow Count :3\n"
            + "No treasure collected yet! \n"
            + "Location Description :\n"
            + "Location id :7\n"
            + "Location type :Cave\n"
            + "Arrows at location 0\n"
            + "The connections for the location are :\n"
            + "NORTH: ID -> 4\n"
            + "No treasure in this location\n"
            + "Enter your choice: Move{m}, Shoot Arrow{s}, Pick{p}, Quit{q}:\n"
            + "\n"
            + "In which direction you want to move? [NORTH]\n"
            + "\n"
            + "Name: Player1\n"
            + "Arrow Count :3\n"
            + "No treasure collected yet! \n"
            + "Location Description :\n"
            + "Location id :4\n"
            + "Location type :Tunnel\n"
            + "Arrows at location 0\n"
            + "The connections for the location are :\n"
            + "SOUTH: ID -> 7\n"
            + "EAST: ID -> 5\n"
            + "No treasure in this location\n"
            + "Enter your choice: Move{m}, Shoot Arrow{s}, Pick{p}, Quit{q}:\n"
            + "\n"
            + "In which direction you want to move? [SOUTH, EAST]\n"
            + "\n"
            + "Name: Player1\n"
            + "Arrow Count :3\n"
            + "No treasure collected yet! \n"
            + "Location Description :\n"
            + "Location id :5\n"
            + "Location type :Tunnel\n"
            + "Arrows at location 0\n"
            + "The connections for the location are :\n"
            + "NORTH: ID -> 2\n"
            + "WEST: ID -> 4\n"
            + "No treasure in this location\n"
            + "There is a weak smell of something deadly nearby\n"
            + "Enter your choice: Move{m}, Shoot Arrow{s}, Pick{p}, Quit{q}:\n"
            + "\n"
            + "In which direction you want to move? [NORTH, WEST]\n"
            + "\n"
            + "Name: Player1\n"
            + "Arrow Count :3\n"
            + "No treasure collected yet! \n"
            + "Location Description :\n"
            + "Location id :2\n"
            + "Location type :Cave\n"
            + "Arrows at location 0\n"
            + "The connections for the location are :\n"
            + "SOUTH: ID -> 5\n"
            + "EAST: ID -> 3\n"
            + "WEST: ID -> 1\n"
            + "The treasure at the location is\n"
            + "RUBY\n"
            + "There is a strong deadly smell.\n"
            + "Enter your choice: Move{m}, Shoot Arrow{s}, Pick{p}, Quit{q}:\n"
            + "\n"
            + "You picked the treasure present at the location.\n"
            + "Name: Player1\n"
            + "Arrow Count :3\n"
            + "Treasure Collected :\n"
            + "RUBY: 1\n"
            + "Location Description :\n"
            + "Location id :2\n"
            + "Location type :Cave\n"
            + "Arrows at location 0\n"
            + "The connections for the location are :\n"
            + "SOUTH: ID -> 5\n"
            + "EAST: ID -> 3\n"
            + "WEST: ID -> 1\n"
            + "No treasure in this location\n"
            + "There is a strong deadly smell.\n"
            + "Enter your choice: Move{m}, Shoot Arrow{s}, Pick{p}, Quit{q}:\n"
            + "\n"
            + "In which direction you want to move? [SOUTH, EAST, WEST]\n"
            + "\n"
            + "Name: Player1\n"
            + "Arrow Count :3\n"
            + "Treasure Collected :\n"
            + "RUBY: 1\n"
            + "Location Description :\n"
            + "Location id :3\n"
            + "Location type :Tunnel\n"
            + "Arrows at location 0\n"
            + "The connections for the location are :\n"
            + "SOUTH: ID -> 6\n"
            + "WEST: ID -> 2\n"
            + "No treasure in this location\n"
            + "There is a weak smell of something deadly nearby\n"
            + "Enter your choice: Move{m}, Shoot Arrow{s}, Pick{p}, Quit{q}:\n"
            + "\n"
            + "In which direction you want to move? [SOUTH, WEST]\n"
            + "\n"
            + "Name: Player1\n"
            + "Arrow Count :3\n"
            + "Treasure Collected :\n"
            + "RUBY: 1\n"
            + "Location Description :\n"
            + "Location id :6\n"
            + "Location type :Tunnel\n"
            + "Arrows at location 0\n"
            + "The connections for the location are :\n"
            + "SOUTH: ID -> 9\n"
            + "NORTH: ID -> 3\n"
            + "No treasure in this location\n"
            + "There is a weak smell of something deadly nearby\n"
            + "Enter your choice: Move{m}, Shoot Arrow{s}, Pick{p}, Quit{q}:\n"
            + "\n"
            + "In which direction you want to move? [SOUTH, NORTH]\n"
            + "\n"
            + "Name: Player1\n"
            + "Arrow Count :3\n"
            + "Treasure Collected :\n"
            + "RUBY: 1\n"
            + "Location Description :\n"
            + "Location id :9\n"
            + "Location type :Tunnel\n"
            + "Arrows at location 1\n"
            + "The connections for the location are :\n"
            + "NORTH: ID -> 6\n"
            + "WEST: ID -> 8\n"
            + "No treasure in this location\n"
            + "There is a strong deadly smell.\n"
            + "Enter your choice: Move{m}, Shoot Arrow{s}, Pick{p}, Quit{q}:\n"
            + "\n"
            + "You picked the arrows present at the location.\n"
            + "Name: Player1\n"
            + "Arrow Count :4\n"
            + "Treasure Collected :\n"
            + "RUBY: 1\n"
            + "Location Description :\n"
            + "Location id :9\n"
            + "Location type :Tunnel\n"
            + "Arrows at location 0\n"
            + "The connections for the location are :\n"
            + "NORTH: ID -> 6\n"
            + "WEST: ID -> 8\n"
            + "No treasure in this location\n"
            + "There is a strong deadly smell.\n"
            + "Enter your choice: Move{m}, Shoot Arrow{s}, Pick{p}, Quit{q}:\n"
            + "\n"
            + "In which direction you want to shoot?\n"
            + "\n"
            + "Enter the distance for shooting the arrow: \n"
            + "\n"
            + "You hit the monster!!\n"
            + "Name: Player1\n"
            + "Arrow Count :3\n"
            + "Treasure Collected :\n"
            + "RUBY: 1\n"
            + "Location Description :\n"
            + "Location id :9\n"
            + "Location type :Tunnel\n"
            + "Arrows at location 0\n"
            + "The connections for the location are :\n"
            + "NORTH: ID -> 6\n"
            + "WEST: ID -> 8\n"
            + "No treasure in this location\n"
            + "There is a strong deadly smell.\n"
            + "Enter your choice: Move{m}, Shoot Arrow{s}, Pick{p}, Quit{q}:\n"
            + "\n"
            + "Quitting game !", log.toString());
  }

  @Test
  public void testNonWrapEntireTraversalPlayerDies() {
    StringReader input = new StringReader("m n m e m n p m e m s m s p s w 1 m w");
    Appendable log = new StringBuffer();
    DungeonController controller = new Controller(input, log);
    controller.play(dungeon);
    assertEquals("\nName: Player1\n"
            + "Arrow Count :3\n"
            + "No treasure collected yet! \n"
            + "Location Description :\n"
            + "Location id :7\n"
            + "Location type :Cave\n"
            + "Arrows at location 0\n"
            + "The connections for the location are :\n"
            + "NORTH: ID -> 4\n"
            + "No treasure in this location\n"
            + "Enter your choice: Move{m}, Shoot Arrow{s}, Pick{p}, Quit{q}:\n"
            + "\n"
            + "In which direction you want to move? [NORTH]\n"
            + "\n"
            + "Name: Player1\n"
            + "Arrow Count :3\n"
            + "No treasure collected yet! \n"
            + "Location Description :\n"
            + "Location id :4\n"
            + "Location type :Tunnel\n"
            + "Arrows at location 0\n"
            + "The connections for the location are :\n"
            + "SOUTH: ID -> 7\n"
            + "EAST: ID -> 5\n"
            + "No treasure in this location\n"
            + "Enter your choice: Move{m}, Shoot Arrow{s}, Pick{p}, Quit{q}:\n"
            + "\n"
            + "In which direction you want to move? [SOUTH, EAST]\n"
            + "\n"
            + "Name: Player1\n"
            + "Arrow Count :3\n"
            + "No treasure collected yet! \n"
            + "Location Description :\n"
            + "Location id :5\n"
            + "Location type :Tunnel\n"
            + "Arrows at location 0\n"
            + "The connections for the location are :\n"
            + "NORTH: ID -> 2\n"
            + "WEST: ID -> 4\n"
            + "No treasure in this location\n"
            + "There is a weak smell of something deadly nearby\n"
            + "Enter your choice: Move{m}, Shoot Arrow{s}, Pick{p}, Quit{q}:\n"
            + "\n"
            + "In which direction you want to move? [NORTH, WEST]\n"
            + "\n"
            + "Name: Player1\n"
            + "Arrow Count :3\n"
            + "No treasure collected yet! \n"
            + "Location Description :\n"
            + "Location id :2\n"
            + "Location type :Cave\n"
            + "Arrows at location 0\n"
            + "The connections for the location are :\n"
            + "SOUTH: ID -> 5\n"
            + "EAST: ID -> 3\n"
            + "WEST: ID -> 1\n"
            + "The treasure at the location is\n"
            + "RUBY\n"
            + "There is a strong deadly smell.\n"
            + "Enter your choice: Move{m}, Shoot Arrow{s}, Pick{p}, Quit{q}:\n"
            + "\n"
            + "You picked the treasure present at the location.\n"
            + "Name: Player1\n"
            + "Arrow Count :3\n"
            + "Treasure Collected :\n"
            + "RUBY: 1\n"
            + "Location Description :\n"
            + "Location id :2\n"
            + "Location type :Cave\n"
            + "Arrows at location 0\n"
            + "The connections for the location are :\n"
            + "SOUTH: ID -> 5\n"
            + "EAST: ID -> 3\n"
            + "WEST: ID -> 1\n"
            + "No treasure in this location\n"
            + "There is a strong deadly smell.\n"
            + "Enter your choice: Move{m}, Shoot Arrow{s}, Pick{p}, Quit{q}:\n"
            + "\n"
            + "In which direction you want to move? [SOUTH, EAST, WEST]\n"
            + "\n"
            + "Name: Player1\n"
            + "Arrow Count :3\n"
            + "Treasure Collected :\n"
            + "RUBY: 1\n"
            + "Location Description :\n"
            + "Location id :3\n"
            + "Location type :Tunnel\n"
            + "Arrows at location 0\n"
            + "The connections for the location are :\n"
            + "SOUTH: ID -> 6\n"
            + "WEST: ID -> 2\n"
            + "No treasure in this location\n"
            + "There is a weak smell of something deadly nearby\n"
            + "Enter your choice: Move{m}, Shoot Arrow{s}, Pick{p}, Quit{q}:\n"
            + "\n"
            + "In which direction you want to move? [SOUTH, WEST]\n"
            + "\n"
            + "Name: Player1\n"
            + "Arrow Count :3\n"
            + "Treasure Collected :\n"
            + "RUBY: 1\n"
            + "Location Description :\n"
            + "Location id :6\n"
            + "Location type :Tunnel\n"
            + "Arrows at location 0\n"
            + "The connections for the location are :\n"
            + "SOUTH: ID -> 9\n"
            + "NORTH: ID -> 3\n"
            + "No treasure in this location\n"
            + "There is a weak smell of something deadly nearby\n"
            + "Enter your choice: Move{m}, Shoot Arrow{s}, Pick{p}, Quit{q}:\n"
            + "\n"
            + "In which direction you want to move? [SOUTH, NORTH]\n"
            + "\n"
            + "Name: Player1\n"
            + "Arrow Count :3\n"
            + "Treasure Collected :\n"
            + "RUBY: 1\n"
            + "Location Description :\n"
            + "Location id :9\n"
            + "Location type :Tunnel\n"
            + "Arrows at location 1\n"
            + "The connections for the location are :\n"
            + "NORTH: ID -> 6\n"
            + "WEST: ID -> 8\n"
            + "No treasure in this location\n"
            + "There is a strong deadly smell.\n"
            + "Enter your choice: Move{m}, Shoot Arrow{s}, Pick{p}, Quit{q}:\n"
            + "\n"
            + "You picked the arrows present at the location.\n"
            + "Name: Player1\n"
            + "Arrow Count :4\n"
            + "Treasure Collected :\n"
            + "RUBY: 1\n"
            + "Location Description :\n"
            + "Location id :9\n"
            + "Location type :Tunnel\n"
            + "Arrows at location 0\n"
            + "The connections for the location are :\n"
            + "NORTH: ID -> 6\n"
            + "WEST: ID -> 8\n"
            + "No treasure in this location\n"
            + "There is a strong deadly smell.\n"
            + "Enter your choice: Move{m}, Shoot Arrow{s}, Pick{p}, Quit{q}:\n"
            + "\n"
            + "In which direction you want to shoot?\n"
            + "\n"
            + "Enter the distance for shooting the arrow: \n"
            + "\n"
            + "You hit the monster!!\n"
            + "Name: Player1\n"
            + "Arrow Count :3\n"
            + "Treasure Collected :\n"
            + "RUBY: 1\n"
            + "Location Description :\n"
            + "Location id :9\n"
            + "Location type :Tunnel\n"
            + "Arrows at location 0\n"
            + "The connections for the location are :\n"
            + "NORTH: ID -> 6\n"
            + "WEST: ID -> 8\n"
            + "No treasure in this location\n"
            + "There is a strong deadly smell.\n"
            + "Enter your choice: Move{m}, Shoot Arrow{s}, Pick{p}, Quit{q}:\n"
            + "\n"
            + "In which direction you want to move? [NORTH, WEST]\n"
            + "\n"
            + "You just died!\n"
            + "Good Luck Next Time", log.toString());
  }

  @Test
  public void testNonWrapPlayerWins() {
    DungeonWithMonster dungeon2 = new DungeonMonsterImpl(2, 6, 0, 30,
            false, 1, 4);
    StringReader input = new StringReader("m w m n p t p a m w p a m s m w s w 1 s w 1 m w q");
    Appendable log = new StringBuffer();
    DungeonController controller = new Controller(input, log);
    controller.play(dungeon2);
    assertEquals("\nName: Player1\n"
            + "Arrow Count :3\n"
            + "No treasure collected yet! \n"
            + "Location Description :\n"
            + "Location id :26\n"
            + "Location type :Cave\n"
            + "Arrows at location 0\n"
            + "The connections for the location are :\n"
            + "WEST: ID -> 25\n"
            + "No treasure in this location\n"
            + "Enter your choice: Move{m}, Shoot Arrow{s}, Pick{p}, Quit{q}:\n"
            + "\n"
            + "In which direction you want to move? [WEST]\n"
            + "\n"
            + "Name: Player1\n"
            + "Arrow Count :3\n"
            + "No treasure collected yet! \n"
            + "Location Description :\n"
            + "Location id :25\n"
            + "Location type :Tunnel\n"
            + "Arrows at location 0\n"
            + "The connections for the location are :\n"
            + "EAST: ID -> 26\n"
            + "NORTH: ID -> 19\n"
            + "No treasure in this location\n"
            + "Enter your choice: Move{m}, Shoot Arrow{s}, Pick{p}, Quit{q}:\n"
            + "\n"
            + "In which direction you want to move? [EAST, NORTH]\n"
            + "\n"
            + "Name: Player1\n"
            + "Arrow Count :3\n"
            + "No treasure collected yet! \n"
            + "Location Description :\n"
            + "Location id :19\n"
            + "Location type :Cave\n"
            + "Arrows at location 2\n"
            + "The connections for the location are :\n"
            + "SOUTH: ID -> 25\n"
            + "EAST: ID -> 20\n"
            + "WEST: ID -> 18\n"
            + "The treasure at the location is\n"
            + "SAPPHIRE\n"
            + "RUBY\n"
            + "Enter your choice: Move{m}, Shoot Arrow{s}, Pick{p}, Quit{q}:\n"
            + "\n"
            + "What do you want to pick? Treasure[t], Arrow[a]\n"
            + "\n"
            + "You picked the treasure present at the location.\n"
            + "Name: Player1\n"
            + "Arrow Count :3\n"
            + "Treasure Collected :\n"
            + "RUBY: 1\n"
            + "SAPPHIRE: 1\n"
            + "Location Description :\n"
            + "Location id :19\n"
            + "Location type :Cave\n"
            + "Arrows at location 2\n"
            + "The connections for the location are :\n"
            + "SOUTH: ID -> 25\n"
            + "EAST: ID -> 20\n"
            + "WEST: ID -> 18\n"
            + "No treasure in this location\n"
            + "Enter your choice: Move{m}, Shoot Arrow{s}, Pick{p}, Quit{q}:\n"
            + "\n"
            + "You picked the arrows present at the location.\n"
            + "Name: Player1\n"
            + "Arrow Count :5\n"
            + "Treasure Collected :\n"
            + "RUBY: 1\n"
            + "SAPPHIRE: 1\n"
            + "Location Description :\n"
            + "Location id :19\n"
            + "Location type :Cave\n"
            + "Arrows at location 0\n"
            + "The connections for the location are :\n"
            + "SOUTH: ID -> 25\n"
            + "EAST: ID -> 20\n"
            + "WEST: ID -> 18\n"
            + "No treasure in this location\n"
            + "Enter your choice: Move{m}, Shoot Arrow{s}, Pick{p}, Quit{q}:\n"
            + "\n"
            + "Invalid move.\n"
            + "Name: Player1\n"
            + "Arrow Count :5\n"
            + "Treasure Collected :\n"
            + "RUBY: 1\n"
            + "SAPPHIRE: 1\n"
            + "Location Description :\n"
            + "Location id :19\n"
            + "Location type :Cave\n"
            + "Arrows at location 0\n"
            + "The connections for the location are :\n"
            + "SOUTH: ID -> 25\n"
            + "EAST: ID -> 20\n"
            + "WEST: ID -> 18\n"
            + "No treasure in this location\n"
            + "Enter your choice: Move{m}, Shoot Arrow{s}, Pick{p}, Quit{q}:\n"
            + "\n"
            + "In which direction you want to move? [SOUTH, EAST, WEST]\n"
            + "\n"
            + "Name: Player1\n"
            + "Arrow Count :5\n"
            + "Treasure Collected :\n"
            + "RUBY: 1\n"
            + "SAPPHIRE: 1\n"
            + "Location Description :\n"
            + "Location id :18\n"
            + "Location type :Tunnel\n"
            + "Arrows at location 2\n"
            + "The connections for the location are :\n"
            + "SOUTH: ID -> 24\n"
            + "EAST: ID -> 19\n"
            + "No treasure in this location\n"
            + "Enter your choice: Move{m}, Shoot Arrow{s}, Pick{p}, Quit{q}:\n"
            + "\n"
            + "You picked the arrows present at the location.\n"
            + "Name: Player1\n"
            + "Arrow Count :7\n"
            + "Treasure Collected :\n"
            + "RUBY: 1\n"
            + "SAPPHIRE: 1\n"
            + "Location Description :\n"
            + "Location id :18\n"
            + "Location type :Tunnel\n"
            + "Arrows at location 0\n"
            + "The connections for the location are :\n"
            + "SOUTH: ID -> 24\n"
            + "EAST: ID -> 19\n"
            + "No treasure in this location\n"
            + "Enter your choice: Move{m}, Shoot Arrow{s}, Pick{p}, Quit{q}:\n"
            + "\n"
            + "Invalid move.\n"
            + "Name: Player1\n"
            + "Arrow Count :7\n"
            + "Treasure Collected :\n"
            + "RUBY: 1\n"
            + "SAPPHIRE: 1\n"
            + "Location Description :\n"
            + "Location id :18\n"
            + "Location type :Tunnel\n"
            + "Arrows at location 0\n"
            + "The connections for the location are :\n"
            + "SOUTH: ID -> 24\n"
            + "EAST: ID -> 19\n"
            + "No treasure in this location\n"
            + "Enter your choice: Move{m}, Shoot Arrow{s}, Pick{p}, Quit{q}:\n"
            + "\n"
            + "In which direction you want to move? [SOUTH, EAST]\n"
            + "\n"
            + "Name: Player1\n"
            + "Arrow Count :7\n"
            + "Treasure Collected :\n"
            + "RUBY: 1\n"
            + "SAPPHIRE: 1\n"
            + "Location Description :\n"
            + "Location id :24\n"
            + "Location type :Tunnel\n"
            + "Arrows at location 0\n"
            + "The connections for the location are :\n"
            + "NORTH: ID -> 18\n"
            + "WEST: ID -> 23\n"
            + "No treasure in this location\n"
            + "There is a weak smell of something deadly nearby\n"
            + "Enter your choice: Move{m}, Shoot Arrow{s}, Pick{p}, Quit{q}:\n"
            + "\n"
            + "In which direction you want to move? [NORTH, WEST]\n"
            + "\n"
            + "Name: Player1\n"
            + "Arrow Count :7\n"
            + "Treasure Collected :\n"
            + "RUBY: 1\n"
            + "SAPPHIRE: 1\n"
            + "Location Description :\n"
            + "Location id :23\n"
            + "Location type :Cave\n"
            + "Arrows at location 0\n"
            + "The connections for the location are :\n"
            + "EAST: ID -> 24\n"
            + "NORTH: ID -> 17\n"
            + "WEST: ID -> 22\n"
            + "No treasure in this location\n"
            + "There is a strong deadly smell.\n"
            + "Enter your choice: Move{m}, Shoot Arrow{s}, Pick{p}, Quit{q}:\n"
            + "\n"
            + "In which direction you want to shoot?\n"
            + "\n"
            + "Enter the distance for shooting the arrow: \n"
            + "\n"
            + "You hit the monster!!\n"
            + "Name: Player1\n"
            + "Arrow Count :6\n"
            + "Treasure Collected :\n"
            + "RUBY: 1\n"
            + "SAPPHIRE: 1\n"
            + "Location Description :\n"
            + "Location id :23\n"
            + "Location type :Cave\n"
            + "Arrows at location 0\n"
            + "The connections for the location are :\n"
            + "EAST: ID -> 24\n"
            + "NORTH: ID -> 17\n"
            + "WEST: ID -> 22\n"
            + "No treasure in this location\n"
            + "There is a strong deadly smell.\n"
            + "Enter your choice: Move{m}, Shoot Arrow{s}, Pick{p}, Quit{q}:\n"
            + "\n"
            + "In which direction you want to shoot?\n"
            + "\n"
            + "Enter the distance for shooting the arrow: \n"
            + "\n"
            + "You hit the monster!!\n"
            + "Name: Player1\n"
            + "Arrow Count :5\n"
            + "Treasure Collected :\n"
            + "RUBY: 1\n"
            + "SAPPHIRE: 1\n"
            + "Location Description :\n"
            + "Location id :23\n"
            + "Location type :Cave\n"
            + "Arrows at location 0\n"
            + "The connections for the location are :\n"
            + "EAST: ID -> 24\n"
            + "NORTH: ID -> 17\n"
            + "WEST: ID -> 22\n"
            + "No treasure in this location\n"
            + "Enter your choice: Move{m}, Shoot Arrow{s}, Pick{p}, Quit{q}:\n"
            + "\n"
            + "In which direction you want to move? [EAST, NORTH, WEST]\n"
            + "\n"
            + "You won! Congratulations!", log.toString());

  }

  @Test
  public void testWrappingPlayerDies() {
    DungeonWithMonster dungeon3 = new DungeonMonsterImpl(2, 6, 0,
            20, true, 2, 5);

    StringReader input = new StringReader("p m w m w m s");
    Appendable log = new StringBuffer();
    DungeonController controller = new Controller(input, log);
    controller.play(dungeon3);
    assertEquals("\nName: Player1\n"
            + "Arrow Count :3\n"
            + "No treasure collected yet! \n"
            + "Location Description :\n"
            + "Location id :16\n"
            + "Location type :Cave\n"
            + "Arrows at location 0\n"
            + "The connections for the location are :\n"
            + "WEST: ID -> 15\n"
            + "The treasure at the location is\n"
            + "SAPPHIRE\n"
            + "RUBY\n"
            + "Enter your choice: Move{m}, Shoot Arrow{s}, Pick{p}, Quit{q}:\n"
            + "\n"
            + "You picked the treasure present at the location.\n"
            + "Name: Player1\n"
            + "Arrow Count :3\n"
            + "Treasure Collected :\n"
            + "SAPPHIRE: 1\n"
            + "RUBY: 1\n"
            + "Location Description :\n"
            + "Location id :16\n"
            + "Location type :Cave\n"
            + "Arrows at location 0\n"
            + "The connections for the location are :\n"
            + "WEST: ID -> 15\n"
            + "No treasure in this location\n"
            + "Enter your choice: Move{m}, Shoot Arrow{s}, Pick{p}, Quit{q}:\n"
            + "\n"
            + "In which direction you want to move? [WEST]\n"
            + "\n"
            + "Name: Player1\n"
            + "Arrow Count :3\n"
            + "Treasure Collected :\n"
            + "SAPPHIRE: 1\n"
            + "RUBY: 1\n"
            + "Location Description :\n"
            + "Location id :15\n"
            + "Location type :Tunnel\n"
            + "Arrows at location 0\n"
            + "The connections for the location are :\n"
            + "EAST: ID -> 16\n"
            + "WEST: ID -> 20\n"
            + "No treasure in this location\n"
            + "There is a weak smell of something deadly nearby\n"
            + "Enter your choice: Move{m}, Shoot Arrow{s}, Pick{p}, Quit{q}:\n"
            + "\n"
            + "In which direction you want to move? [EAST, WEST]\n"
            + "\n"
            + "Name: Player1\n"
            + "Arrow Count :3\n"
            + "Treasure Collected :\n"
            + "SAPPHIRE: 1\n"
            + "RUBY: 1\n"
            + "Location Description :\n"
            + "Location id :20\n"
            + "Location type :Cave\n"
            + "Arrows at location 0\n"
            + "The connections for the location are :\n"
            + "SOUTH: ID -> 26\n"
            + "EAST: ID -> 15\n"
            + "WEST: ID -> 19\n"
            + "No treasure in this location\n"
            + "There is a strong deadly smell.\n"
            + "Enter your choice: Move{m}, Shoot Arrow{s}, Pick{p}, Quit{q}:\n"
            + "\n"
            + "In which direction you want to move? [SOUTH, EAST, WEST]\n"
            + "\n"
            + "You just died!\n"
            + "Good Luck Next Time", log.toString());
  }

}
